version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 10
  assignees:
  - manferlo81
  versioning-strategy: increase
