env:
  browser: true
  es6: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

settings:
  react:
    version: "16.13"

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  __static: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json

plugins:
  - react
  - react-hooks
  - "@typescript-eslint"

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - windows

  quotes:
    - error
    - single

  comma-dangle:
    - error
    - always-multiline

  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0

  no-useless-rename: error
  object-shorthand: error

  jsx-quotes: error

  "@typescript-eslint/explicit-function-return-type": off

  semi: "off"
  "@typescript-eslint/semi":
    - error
    - always
